const typeChat = {
  GET_ROOM_LIST: 'GET_ROOM_LIST',
  GET_ROOM_LIST_SUCCESS: 'GET_ROOM_LIST_SUCCESS',
  GET_DETAIL_LIST_CHAT: 'GET_DETAIL_LIST_CHAT',
  GET_DETAIL_LIST_CHAT_SUCCESS: 'GET_DETAIL_LIST_CHAT_SUCCESS',
  SAVE_ID_COMPANY: 'SAVE_ID_COMPANY',
  SAVE_ID_ROOMCHAT: 'SAVE_ID_ROOMCHAT',
  GET_DETAIL_MESSAGE_SOCKET: 'GET_DETAIL_MESSAGE_SOCKET',
  GET_DETAIL_MESSAGE_SOCKET_SUCCESS: 'GET_DETAIL_MESSAGE_SOCKET_SUCCESS',
  SAVE_MESSAGE_REPLY: 'SAVE_MESSAGE_REPLY',
  RESET_DATA: 'RESET_DATA',

  DELETE_MESSAGE: 'DELETE_MESSAGE',
  PIN_MESSAGE: 'PIN_MESSAGE',
};

export {typeChat};
