const typeChat = {
  GET_ROOM_LIST: 'GET_ROOM_LIST',
  GET_ROOM_LIST_SUCCESS: 'GET_ROOM_LIST_SUCCESS',
  GET_DETAIL_LIST_CHAT: 'GET_DETAIL_LIST_CHAT',
  GET_DETAIL_LIST_CHAT_SUCCESS: 'GET_DETAIL_LIST_CHAT_SUCCESS',
  SAVE_ID_COMPANY: 'SAVE_ID_COMPANY',
};

export {typeChat};
