const typeChat = {
  GET_ROOM_LIST: 'GET_ROOM_LIST',
  GET_ROOM_LIST_SUCCESS: 'GET_ROOM_LIST_SUCCESS',
  GET_DETAIL_LIST_CHAT: 'GET_DETAIL_LIST_CHAT',
  GET_DETAIL_LIST_CHAT_SUCCESS: 'GET_DETAIL_LIST_CHAT_SUCCESS',
  SAVE_ID_COMPANY: 'SAVE_ID_COMPANY',
  SAVE_ID_ROOMCHAT: 'SAVE_ID_ROOMCHAT',
  GET_DETAIL_MESSAGE_SOCKET: 'GET_DETAIL_MESSAGE_SOCKET',
  GET_DETAIL_MESSAGE_SOCKET_CURRENT: 'GET_DETAIL_MESSAGE_SOCKET_CURRENT',
  GET_DETAIL_MESSAGE_SOCKET_SUCCESS: 'GET_DETAIL_MESSAGE_SOCKET_SUCCESS',
  SAVE_MESSAGE_REPLY: 'SAVE_MESSAGE_REPLY',
  SAVE_MESSAGE_EDIT: 'SAVE_MESSAGE_EDIT',
  SAVE_MESSAGE_QUOTE: 'SAVE_MESSAGE_QUOTE',
  RESET_DATA: 'RESET_DATA',

  DELETE_MESSAGE: 'DELETE_MESSAGE',
  EDIT_MESSAGE: 'EDIT_MESSAGE',
  PIN_MESSAGE: 'PIN_MESSAGE',
  FETCH_RESULT_SEARCH_MESSAGE:
    'FETCH_RESULT_SEARCH_MESSAGE_RESULT_SEARCH_MESSAGE',
  FETCH_RESULT_SEARCH_MESSAGE_RED_LINE: 'FETCH_RESULT_SEARCH_MESSAGE_RED_LINE',
  RESULT_SEARCH_MESSAGE: 'RESULT_SEARCH_MESSAGE',
  SAVE_MESSAGE_SEARCH: 'SAVE_MESSAGE_SEARCH',
  UPDATE_MESSAGE_SEEN: 'UPDATE_MESSAGE_SEEN',
  UPDATE_MESSAGE_SEEN_SUCCESS: 'UPDATE_MESSAGE_SEEN_SUCCESS',
  GET_DETAIL_MESSAGE_SOCKET_SEEN: 'GET_DETAIL_MESSAGE_SOCKET_SEEN',
  GET_DETAIL_MESSAGE_SOCKET_SEEN_SUCCESS:
    'GET_DETAIL_MESSAGE_SOCKET_SEEN_SUCCESS',
  FETCH_RESULT_SEARCH_MESSAGE_LIST_ROOM:
    'FETCH_RESULT_SEARCH_MESSAGE_LIST_ROOM',
  IS_GET_INFO_ROOM: 'IS_GET_INFO_ROOM',
  FETCH_RESULT_SEARCH_MESSAGE_LIST_FILE:
    'FETCH_RESULT_SEARCH_MESSAGE_LIST_FILE',
  EDIT_MESSAGE_REACTION: 'EDIT_MESSAGE_REACTION',
  DETAIL_ROOM_SOCKET: 'DETAIL_ROOM_SOCKET',
  DETAIL_ROOM_SOCKET_SUCCESS: 'DETAIL_ROOM_SOCKET_SUCCESS',
  SHOW_HIDE_MODAL_FILTER_LISTCHAT: 'SHOW_HIDE_MODAL_FILTER_LISTCHAT',
  GET_UNREAD_MESSAGE_COUNT_ALL: 'GET_UNREAD_MESSAGE_COUNT_ALL',

  SAVE_TYPE_FILTER: 'SAVE_TYPE_FILTER',
  SAVE_CATEGORY_FILTER: 'SAVE_CATEGORY_FILTER',
  SAVE_STATUS_FILTER: 'SAVE_STATUS_FILTER',
  GET_UNREAD_MESSAGE_COUNT_ALL_SUCCESS: 'GET_UNREAD_MESSAGE_COUNT_ALL_SUCCESS',
  LOG_MESSAGE: 'LOG_MESSAGE',
};

export {typeChat};
