export const CHAT_STAMP_ICONS = [
  {id: 1, url: require('./chat-stamp1.png')},
  {id: 2, url: require('./chat-stamp2.png')},
  {id: 3, url: require('./chat-stamp3.png')},
  {id: 4, url: require('./chat-stamp4.png')},
  {id: 5, url: require('./chat-stamp5.png')},
  {id: 6, url: require('./chat-stamp6.png')},
  {id: 7, url: require('./chat-stamp7.png')},
  {id: 8, url: require('./chat-stamp8.png')},
  {id: 9, url: require('./chat-stamp9.png')},
  {id: 10, url: require('./chat-stamp10.png')},
  {id: 11, url: require('./chat-stamp11.png')},
  {id: 12, url: require('./chat-stamp12.png')},
  {id: 13, url: require('./chat-stamp13.png')},
  {id: 14, url: require('./chat-stamp14.png')},
  {id: 15, url: require('./chat-stamp15.png')},
  {id: 16, url: require('./chat-stamp16.png')},
  {id: 17, url: require('./chat-stamp17.png')},
  {id: 18, url: require('./chat-stamp18.png')},
  {id: 19, url: require('./chat-stamp19.png')},
  {id: 20, url: require('./chat-stamp20.png')},
  {id: 21, url: require('./chat-stamp21.png')},
  {id: 22, url: require('./chat-stamp22.png')},
  {id: 23, url: require('./chat-stamp23.png')},
  {id: 24, url: require('./chat-stamp24.png')},
  {id: 25, url: require('./chat-stamp25.png')},
  {id: 26, url: require('./chat-stamp26.png')},
  {id: 27, url: require('./chat-stamp27.png')},
  {id: 28, url: require('./chat-stamp28.png')},
] as const;

export const CHAT_STAMP_URLS: {[key: number]: string} = {
  1: require('./chat-stamp1.png'),
  2: require('./chat-stamp2.png'),
  3: require('./chat-stamp3.png'),
  4: require('./chat-stamp4.png'),
  5: require('./chat-stamp5.png'),
  6: require('./chat-stamp6.png'),
  7: require('./chat-stamp7.png'),
  8: require('./chat-stamp8.png'),
  9: require('./chat-stamp9.png'),
  10: require('./chat-stamp10.png'),
  11: require('./chat-stamp11.png'),
  12: require('./chat-stamp12.png'),
  13: require('./chat-stamp13.png'),
  14: require('./chat-stamp14.png'),
  15: require('./chat-stamp15.png'),
  16: require('./chat-stamp16.png'),
  17: require('./chat-stamp17.png'),
  18: require('./chat-stamp18.png'),
  19: require('./chat-stamp19.png'),
  20: require('./chat-stamp20.png'),
  21: require('./chat-stamp21.png'),
  22: require('./chat-stamp22.png'),
  23: require('./chat-stamp23.png'),
  24: require('./chat-stamp24.png'),
  25: require('./chat-stamp25.png'),
  26: require('./chat-stamp26.png'),
  27: require('./chat-stamp27.png'),
  28: require('./chat-stamp28.png'),
} as const;
