const ROUTE_NAME = {
  //auth
  LOGIN: 'LOGIN',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',

  //common
  TAB_SCREEN: 'TAB_SCREEN',
  SPLASH_SCREEN: 'SPLASH_SCREEN',

  //app
  SELECT_COMPANY: 'SELECT_COMPANY',
  LISTCHAT_SCREEN: 'LISTCHAT_SCREEN',
  SETTING_SCREEN: 'SETTING_SCREEN',
  USER_SCREEN: 'USER_SCREEN',
  CREATE_ROOM_CHAT: 'CREATE_ROOM_CHAT',
  DETAIL_CHAT: 'DETAIL_CHAT',
  INFO_ROOM_CHAT: 'INFO_ROOM_CHAT',
  LIST_USER: 'LIST_USER',
  EDIT_ROOM_CHAT: 'EDIT_ROOM_CHAT',
  EDIT_USER: 'EDIT_USER',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  CONFIG_NOTI: 'CONFIG_NOTI',
};

export {ROUTE_NAME};
